--- # Connection
- name: Install packages
  hosts: localhost
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 
  - name: Install telnet
    ansible.builtin.package:
      name: telnet
      state: present
      
  - name: Upgrade All
    ansible.builtin.package:
      name: "*"
      state: latest